// Part05_Vue/Chap01_Component/src/components/A01.Currency.vue
<template>
    <div>
        <h3>1. Currency</h3>
        <br>

        <div>
        Qty: <input type="text" class="form-control" v-model="qty"><br>
        Cost: <input type="text" class="form-control" v-model="cost"><br>
        Country: 
            <select class="form-control" v-model="inCurr">
                <option v-for="item in currencies" :key="item">{{item}}</option>
            </select>
        </div>
        <br>

        <div>
            Total: <span>{{qty * cost}}</span>
        </div>

        <div>
            Total: <span v-for="item in currencies" :key="item">{{item}} {{onTotal(item)}} &nbsp; </span>
        </div>
    </div>
</template>

<script>
export default {
   name: 'currency',        // tab name이 아님. 재귀호출 목적으로 정의
   data: function(){        // 변수 정의. 값이 변경되면 화면 변경됨
    return {
        qty: 3,
        cost: 5,
        inCurr: 'USD',
        currencies: ['USD', 'EUR', 'CNY'],
        rate: {
            USD: 1,
            EUR: 1.35,
            CNY: 6.87
        }
    }
   },
   methods: {                    // method 정의
    onTotal: function(outCurr) {
        return (this.qty * this.cost * this.rate[this.inCurr] / this.rate[outCurr]).toFixed(2);
    }
   }
}
</script>

<style scoped>

</style>

// Part03_Angular/Chap02_Component/src/app/components/A01.Currency.component.ts

import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'a01-currency',
    template: `
        <div>
            <h3>1. Currency</h3>
            <br>

            <div>
            Qty: <input type="text" class="form-control" [(ngModel)]="qty"><br>
            Cost: <input type="text" class="form-control" [(ngModel)]="cost"><br>
            Country: {{inCurr}}
                <select class="form-control" [(ngModel)]="inCurr">
                    <!-- for(let item of currencies) { --->
                    <option *ngFor="let item of currencies">{{item}}</option>
                    <!-- } -->
                </select>
            </div>
            <br>

            <div>
                Total: <span>단방향 바인딩: {{qty * cost}}</span>
            </div>

            <div>
                Total: <span *ngFor="let item of currencies">{{onTotal(item) | currency : item : 'symbol' }} &nbsp;</span>
            </div>
        </div>
    `,
    styles: [``]
})
export class A01CurrencyComponent {

    public qty: number = 3;
    public cost: number = 5;
    public currencies: string[]  = ['USD', 'EUR', 'CNY'];
    public inCurr: string = 'USD';
    public rate: { [key: string]: number } = {
        'USD': 1,
        'EUR': 1.35,
        'CNY': 6.87
    }

    public onTotal(outCurr: string): number {
        return this.qty * this.cost * this.rate[this.inCurr] / this.rate[outCurr]
    }

    constructor() { }
}
