// Part04_React/Chap02_Component/src/App.js

import CurrencyClass from './components/A01.CurrencyClass';
import CurrencyFn from './components/A02.CurrencyFn';
import RefComponent from './components/A03.RefComponent';
import LifyCycle from './components/A04.LifyCycleClass';
import Controlled from './components/A05.ControlledComponent';

function App() {
  return (
    <div className="card-body">
      <Controlled></Controlled>
      <LifyCycle color="orange"></LifyCycle>
      <RefComponent name="BangJa">
        <div>This is App Component Content.</div>
      </RefComponent>
      <CurrencyFn title="Currency Function Component"></CurrencyFn>
      <CurrencyClass title="Currency Class Component"/>
    </div>
  );
}

export default App;

// Part05_Vue/Chap01_Component/src/App.vue
<template>
  <div class="card-body">
    <h1>Vue Components</h1>

    <A03Repeater></A03Repeater>
    <A02Binding></A02Binding>
    <A01Currency></A01Currency>

  </div>
</template>

<style>
  
  h1 { color: orange; }

</style>

<script>
import A01Currency from './components/A01.Currency';
import A02Binding from './components/A02.Binding';
import A03Repeater from './components/A03.Repeater';

export default {
  name: 'App',
  components: {
    A01Currency, A02Binding, A03Repeater, 
  }
}
</script>
